### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ros2/unique_identifier_msgs#7]
This issue tracks the progression of `unique_identifier_msgs` to Quality Level 1. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Vulnerability Disclosure Policy

Documentation
* [x] Per-feature documentation. 
* [x] Per-item documentation in public API. 
    - [x] Hosted
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Checked with `ament_copyright`
* [x] Quality Declaration document

Testing:
* [x] System tests, which cover "features". Tests covering public API, Code coverage, Performance testing.
   - Not required for msg packages
* [x] Package code style: ROS Core
* [x] Uses ament_lint_common

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
* [x] non-ROS dependencies are equivalent level 1

Platform Support
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)

**Comment by chapulina** [comment]
Level 1: https://github.com/ros2/unique_identifier_msgs/pull/17
